### ISSUE TITLE
EC Setup Guide no longer accessible

### ISSUE THREAD

**Issue by ghost** [Enterprise-connect/documentation#17]
Hi team,

It appear the EC Setup Guide (https://github.com/Enterprise-connect/ec-misc-docs/blob/pwof_maint/ec-guide.md) on homepage is no longer accessible since the last changes have been made.

Maybe the link above isnt correct?

**Comment by palokam** [comment]
@phiwoff will fix it

**Comment by phiwoff** [comment]
Thanks for bringing this to our attention, I have updated the references and you should no longer see the 404 going forward. The feedback is very much appreciated!
