### ISSUE TITLE
 - add UAA reference to the settings

### ISSUE THREAD

**Issue by ayasuda2OO3** [Enterprise-connect/documentation#3]
Refer a link to the UAA configuration for EC in this document? https://github.com/Enterprise-connect/ec-misc-docs/blob/master/ec-guide.md

**Comment by phiwoff** [comment]
Will do, Chia. Thanks for the feedback!

**Comment by phiwoff** [comment]
Update:

At the first reference to the UAA, I provide a link to the UAA Service Tile page. When I refer to updating the UAA Client, I provide a link to the Predix toolkit (the only universal method I know of at this time). If users experience difficulties in this area, I will expand upon the UAA documentation to include each and every method for provisioning and updating the UAA Client, including the UAA instance dashboard, CF CLI commands, etc.
