### ISSUE TITLE
SOP - Upgrade Process

### ISSUE THREAD

**Issue by palokam** [Enterprise-connect/documentation#31]
Are you just trying to explain the path for upgrade for customers?

How about Step1 and Step2? if the customers are choose to go more a cautious approach?

**Comment by phiwoff** [comment]
I will address this and provide clarification!

Per our discussion, my plan will be to provide two separate documents to cover the topic. One documents will be aimed towards a user audience, and the other (current) will be aimed towards internal/team.

**Comment by philipwofford** [comment]
While not 'perfect', I believe this is addressed
