### ISSUE TITLE
 - What to do when client got a bad handshake?

### ISSUE THREAD

**Issue by ayasuda2OO3** [Enterprise-connect/documentation#6]
Background: running diego scaling of 5 on both server/gateway for reach-in posgres in CF

problem:
Bad hanshake: (client)
<img width="883" alt="screen shot 2017-10-19 at 11 56 22 pm" src="https://user-images.githubusercontent.com/552253/31808813-a6ca821c-b529-11e7-8543-f54243a3450c.png">

SuperConn cannot be found: (gateway)
<img width="1246" alt="screen shot 2017-10-20 at 12 01 16 am" src="https://user-images.githubusercontent.com/552253/31808847-d979fc10-b529-11e7-8077-d830ffed7db6.png">

Question- what is the course of action to resolve similar issues?

**Comment by phiwoff** [comment]
A bad handshake on the Client has more than one potential cause. In this case, it looks as though the SuperConnection was not established between the Server and Gateway and the time of the request.

**Comment by philipwofford** [comment]
This is now addressed in the documentation. I go over the most likely causes and also how to evaluate those causes via logs and Gateway /health
